application:
  typeDeclarations:

    manufacturingTypes:
      - PRINT
      - HANDMADE

    mediaTypes:
      - ARTICLE
      - BOOK
      - CONTAINED
      - IMAGES
      - ISSUE
      - MICROSCOPE_IMAGES
      - NEWSPAPER
      - OBJECT
      - PART
      - SERIAL
      - SPECTRALLYOPTIMIZED_IMAGES
      - THING
      - UNINDEPENDENT
      - WASSERZEICHEN

    subjectTypes:
      - BY
      - GENRE
      - GEO
      - INST
      - MEETING
      - PERSON
      - SHELFGROUP
      - TIME
      - TITLE
      - TOPIC
      - UNSPECIFIED

    expressionTypes:
      - mainType: ANNIVERSARYPUB
        subType: HANDMADE
      - mainType: ANNIVERSARYPUB
        subType: PRINT
      - mainType: ARTISTBOOK
        subType: HANDMADE
      - mainType: ARTISTBOOK
        subType: PRINT
      - mainType: AUTOGRAPH
        subType: HANDMADE
      - mainType: AUTOGRAPH
        subType: PRINT
      - mainType: BIOGRAPHY
        subType: HANDMADE
      - mainType: BIOGRAPHY
        subType: PRINT
      - mainType: BROADSHEET
        subType: HANDMADE
      - mainType: BROADSHEET
        subType: PRINT
      - mainType: CATALOGUE
        subType: HANDMADE
      - mainType: CATALOGUE
        subType: PRINT
      - mainType: CHILDRENSBOOK
        subType: HANDMADE
      - mainType: CHILDRENSBOOK
        subType: PRINT
      - mainType: COLLECTION
        subType: HANDMADE
      - mainType: COLLECTION
        subType: PRINT
      - mainType: COMMENT
        subType: HANDMADE
      - mainType: COMMENT
        subType: PRINT
      - mainType: DIARY
        subType: HANDMADE
      - mainType: DIARY
        subType: PRINT
      - mainType: DICTIONARY
        subType: HANDMADE
      - mainType: DICTIONARY
        subType: PRINT
      - mainType: DIRECTORY
        subType: HANDMADE
      - mainType: DIRECTORY
        subType: PRINT
      - mainType: FICTION
        subType: HANDMADE
      - mainType: FICTION
        subType: PRINT
      - mainType: GUIDE
        subType: HANDMADE
      - mainType: GUIDE
        subType: PRINT
      - mainType: ILLUSTRATEDBOOK
        subType: HANDMADE
      - mainType: ILLUSTRATEDBOOK
        subType: PRINT
      - mainType: INCUNABULUM
        subType: HANDMADE
      - mainType: INCUNABULUM
        subType: PRINT
      - mainType: JOURNAL
        subType: HANDMADE
      - mainType: JOURNAL
        subType: PRINT
      - mainType: LETTERS
        subType: HANDMADE
      - mainType: LETTERS
        subType: PRINT
      - mainType: MANUSCRIPT
        subType: HANDMADE
      - mainType: MANUSCRIPT
        subType: PRINT
      - mainType: MAP
        subType: HANDMADE
      - mainType: MAP
        subType: PRINT
      - mainType: NEWSPAPER
        subType: HANDMADE
      - mainType: NEWSPAPER
        subType: PRINT
      - mainType: PAPYRUS
        subType: HANDMADE
      - mainType: PAPYRUS
        subType: PRINT
      - mainType: PROCEEDING
        subType: HANDMADE
      - mainType: PROCEEDING
        subType: PRINT
      - mainType: PROCEEDINGS
        subType: HANDMADE
      - mainType: PROCEEDINGS
        subType: PRINT
      - mainType: PUBOFFICIAL
        subType: HANDMADE
      - mainType: PUBOFFICIAL
        subType: PRINT
      - mainType: PAMPHLET
        subType: HANDMADE
      - mainType: PAMPHLET
        subType: PRINT
      - mainType: REPORT
        subType: HANDMADE
      - mainType: REPORT
        subType: PRINT
      - mainType: SCHOOLPROGRAM
        subType: HANDMADE
      - mainType: SCHOOLPROGRAM
        subType: PRINT
      - mainType: SCORE
        subType: HANDMADE
      - mainType: SCORE
        subType: PRINT
      - mainType: SOURCE
        subType: HANDMADE
      - mainType: SOURCE
        subType: PRINT
      - mainType: SPEECH
        subType: HANDMADE
      - mainType: SPEECH
        subType: PRINT
      - mainType: STATISTICS
        subType: HANDMADE
      - mainType: STATISTICS
        subType: PRINT
      - mainType: TEXTBOOK
        subType: HANDMADE
      - mainType: TEXTBOOK
        subType: PRINT
      - mainType: THESIS
        subType: HANDMADE
      - mainType: THESIS
        subType: PRINT
      - mainType: MICROFORM
        subType: PRINT
      - mainType: IMAGE
        subType: HANDMADE
      - mainType: IMAGE
        subType: PRINT
      - mainType: TEXT
        subType: HANDMADE
      - mainType: TEXT
        subType: PRINT
      - mainType: SPATIAL
        subType: HANDMADE
      - mainType: SPATIAL
        subType: PRINT
      - mainType: LIBRETTO
        subType: HANDMADE
      - mainType: LIBRETTO
        subType: PRINT

    titleTypes:
      - mainType: ABBR
        subType: MAIN
      - mainType: ALT
        subType: MAIN
      - mainType: ALT
        subType: SUB
      - mainType: ALT
        subType: PART
      - mainType: FORMER
        subType: MAIN
      - mainType: FORMER
        subType: PART
      - mainType: FORMER
        subType: SUB
      - mainType: HOST
        subType:
      - mainType: SUP
        subType:
      - mainType: MAIN
        subType: MAIN
      - mainType: MAIN
        subType: PART
      - mainType: MAIN
        subType: SUB
      - mainType: PAR
        subType: MAIN
      - mainType: PAR
        subType: PART
      - mainType: PAR
        subType: SUB
      - mainType: TRANS
        subType: MAIN
      - mainType: TRANS
        subType: PART
      - mainType: TRANS
        subType: SUB
      - mainType: UNI
        subType: MAIN
      - mainType: UNI
        subType: PART
      - mainType: UNI
        subType: SUB
      - mainType: ISSN
        subType: MAIN
