include: "https://raw.githubusercontent.com/dbmdz/development/master/ci/.gitlab-ci-base.yml"

stages:
  - check
  - build
  - test
  - publish
  - deploy
  - release

###################
### Stage check ###
###################

check_java_codestyle:
  script:
    - mvn com.coveo:fmt-maven-plugin:check
  stage: check

check_javascript_codestyle:
  before_script:
    - pushd dc-cudami-editor
    - npm install --only=dev
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK11"
  script:
    - npm run format-check
    - popd
  stage: check

####################
### Stage deploy ###
####################

deploy:
  before_script:
    - PROJECT_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
  dependencies:
    - publish_snapshot
  except:
    - tags
  only:
    - master
  script:
    - if [[ ! "$PROJECT_VERSION" =~ .*SNAPSHOT ]]; then exit 0; fi
    - curl -X POST -F token=$TRIGGER_TOKEN -F ref=master -F "variables[PROJECT_VERSION]=$PROJECT_VERSION" $TRIGGER_URL
  stage: deploy
