include:
  - project: "mdz/devops/ci"
    file: "gitlab-ci-base.yml"

image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK17"

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

services:
  - name: "$BUILD_IMAGE_DOCKER_DIND"
    alias: docker

####################
### Stage deploy ###
####################

deploy_dev:
  parallel:
    matrix:
      - PLAYBOOK: [ "cudami/repository-server.yml", "cudami/admin-webapp.yml" ]

deploy_version_to_environment:
  parallel:
    matrix:
      - PLAYBOOK: [ "cudami/repository-server.yml", "cudami/admin-webapp.yml" ]
