include:
  - project: "mdz/devops/ci"
    file: "gitlab-ci-base.yml"

image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK17"

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=.m2/repository --batch-mode -Pcustom-nexus"
  PLAYBOOK: "rest/metadata-service.yml"

verify:
  services:
    - name: "$BUILD_IMAGE_DOCKER_DIND"
      alias: docker
