# local/default

cudami:
  database:
    hostname: localhost
    name: cudami
    password: somepassword
    port: 22222
    username: cudami
  defaults:
    locale: en_US

info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@maven.compiler.source@"
      target: "@maven.compiler.target@"
    project:
      name: "@project.name@"
      groupId: "@project.groupId@"
      artifactId: "@project.artifactId@"
      version: "@project.version@"

jsondoc:
  basePath: "http://localhost:9000"
  version: "@project.version@"
  packages:
    - de.digitalcollections.cudami.server.controller
  # optional configuration
  playgroundEnabled: true
  displayMethodAs: URI

management:
  endpoints:
    web:
      base-path: "/monitoring"
      exposure:
        include: "*"
  server:
    port: 9001

resourceRepository:
  resolved:
    patterns:
      - pattern: '^([0-9a-f]{4})([0-9a-f]{4})-([0-9a-f]{4})-([1-5][0-9a-f]{3})-([89ab][0-9a-f]{3})-([0-9a-f]{4})([0-9a-f]{4})([0-9a-f]{4})$'
        substitutions:
          - '~/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.gif'
          - '~/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.jpg'
          - '~/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.mp3'
          - '~/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.mp4'
          - '~/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.pdf'
          - '~/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.png'

server:
  port: 9000
  server-header: "@project.name@ v@project.version@"

spring:
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: ACTUATOR, SUPERUSER
  servlet:
    multipart:
      # disable resolving request to MultiPartRequest to get direct access to HttpServletRequest
      enabled: false
      max-file-size: -1
      max-request-size: -1
  thymeleaf:
    cache: false
    mode: HTML

---

# PROD
custom:
  database:
    port: 5432

resourceRepository:
  resolved:
    patterns:
      - pattern: '^([0-9a-f]{4})([0-9a-f]{4})-([0-9a-f]{4})-([1-5][0-9a-f]{3})-([89ab][0-9a-f]{3})-([0-9a-f]{4})([0-9a-f]{4})([0-9a-f]{4})$'
        substitutions:
          - '/local/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.gif'
          - '/local/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.jpg'
          - '/local/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.mp3'
          - '/local/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.mp4'
          - '/local/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.pdf'
          - '/local/resourceRepository/dico/$1/$2/$3/$4/$5/$6/$7/$8/$0.png'

spring:
  profiles: PROD
  thymeleaf:
    cache: true