
# Activate /actuator
endpoints:
  hypermedia:
    enabled: true

# Application info /info
info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      groupId: @project.groupId@
      artifactId: @project.artifactId@
      version: @project.version@

# mandatory configuration
jsondoc:
  basePath: https://www.myrestserver.com:8080
  version: 1.0
  packages[0]: de.digitalcollections.cudami.server.webapp.controller
  #packages[1]: com.example.model
  # optional configuration
  playgroundEnabled: true
  displayMethodAs: URI

locales:
  default: "en_US"

management:
  port: 8081
  security:
    enabled: true

server:
  port: 8080

spring:
  profiles:
    active: PROD

---

spring:
  profiles: local

jsondoc:
  basePath: http://localhost:8080

# Deactivate security for sensitive actuator endpoints (DO NOT USE ON A PUBLIC ACCESSIBLE SYSTEM!!!)
management:
  security:
    enabled: false    