custom:
  database:
    hostname: localhost
    name: cudami
    password: somepassword
    port: 22222
    username: cudami

# local/default
endpoints:
  hypermedia:
    enabled: true

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      groupId: @project.groupId@
      artifactId: @project.artifactId@
      version: @project.version@

locales:
  default: "en_US"

management:
  context-path: '/monitoring'
  port: 9001
  security:
    enabled: false

security:
  basic:
    enabled: false
  headers:
    cache: false
    # disables pragma no-cache header

server:
  port: 9000
  server-header: "@project.name@ v@project.version@"

spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML

---

# PROD
custom:
  database:
    port: 5432

management:
  security:
    enabled: true

security:
  user:
    name: admin
    password: secret

spring:
  profiles: PROD
  thymeleaf:
    cache: true