version: '2'
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "cudami"
      POSTGRES_PASSWORD: "somepassword"
      POSTGRES_DB: "cudami"
