resourceRepository:
  resolved:
    patterns:
      # An image pattern resolving example:
      - pattern: ^((\w{4})(\w{4})-(\w{4})-(\w{4})-(\w{4})-(\w{4})(\w{4})(\w{4}))$
        substitutions:
          - 'file:/iiif/upload/image/jp2/$2/$3/$4/$5/$6/$7/$8/$9/resource.jp2'
          - 'file:/iiif/upload/image/jpg/$2/$3/$4/$5/$6/$7/$8/$9/resource.jpg'
          - 'file:/iiif/upload/image/png/$2/$3/$4/$5/$6/$7/$8/$9/resource.png'
          - 'file:/iiif/upload/image/gif/$2/$3/$4/$5/$6/$7/$8/$9/resource.gif'
