resourceRepository:
  resolved:
    patterns:
      # An video pattern resolving example:
      - pattern: ^((\w{4})(\w{4})-(\w{4})-(\w{4})-(\w{4})-(\w{4})(\w{4})(\w{4}))$
        substitutions:
          - 'file:/media/upload/video/mp4/$2/$3/$4/$5/$6/$7/$8/$9/resource.mp4'
